### ISSUE TITLE
final_action::uncaught_exceptions() breaks on brew clang macOS 10.11

### ISSUE THREAD

**Issue by wilhelmtell** [gsl-lite/gsl-lite#116]
I'm not sure whether this issue belongs here, but it seems the Mac Homebrew Clang 6.0.0 libc++ doesn't provide the C++17 `std::uncaught_exceptions()` function on macOS 10.11 El Capitan, and says at compile-time that it's only available starting from macOS 10.12.

The effect is that gsl-lite won't compile on macOS 10.11 with the clang compiler from Mac Homebrew.

If I compile with the stock Apple Clang compiler (clang-800.0.42.1), it does compile though. I'm guessing that's because the stock Apple Clang on macOS 10.11 doesn't support C++17 as much, so gsl-lite doesn't even try to use `std::uncaught_exceptions()` in that case.

**Comment by martinmoene** [comment]
@wilhelmtell As of c83f2a87f4079878c3e949ca4a28300a7d141741 you can use the [standard selection macro](https://github.com/martinmoene/gsl-lite#standard-selection-macro) and specify e.g. `-Dgsl_CPLUSPLUS=201402L` to confine *gsl lite* to C++14.

**Comment by mbeutel** [comment]
`std::uncaught_exceptions()` appeared in Clang 3.7 as per https://libcxx.llvm.org/cxx1z_status.html. There seems to be no problem with Clang 6.0.0 and older versions according to CE:
https://gcc.godbolt.org/z/Y6dGjj

I have no idea what is special about Clang and libc++ in Homebrew. Can somebody shed more light on this? Is there a configuration macro we can check?

**Comment by mbeutel** [comment]
Closing due to lack of feedback. We've recently had some improvements to our `uncaught_exceptions()` polyfill implementation (cf. #286), so this concern may already have been addressed. But if this continues to be a problem, please reopen the issue and provide me with a reproducible test case.
