### ISSUE TITLE
Consider providing sloppy_not_null

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#135]
See M-GSL PR 712

gsl-lite provides
- [`not_null_ic`](https://github.com/martinmoene/gsl-lite/blob/5cbc0e75a1db28c8a198e8c0d26a82fd3c83b602/include/gsl/gsl-lite.hpp#L1151)
- macro
`gsl_CONFIG_NOT_NULL_EXPLICIT_CTOR`.

**Comment by mbeutel** [comment]
I agree with https://github.com/microsoft/GSL/pull/712#issuecomment-410003465 that `sloppy_not_null<>` is just an aid for transition and probably shouldn't be in the library.

I'm not sure if `not_null_ic<>` was also meant to be a transitional feature; if so, perhaps we should mark it `[[deprecated("transition only; migrate to not_null<>")]]`?
