### ISSUE TITLE
Conan package updated after release (and without version change)

### ISSUE THREAD

**Issue by nathanaelg** [gsl-lite/gsl-lite#159]
I recently noticed that the contents of the `0.34.0` conan package had changed without any change in version number. I'm not sure how you've configured your CI (I can't actually see where/if the conan package build is being done automatically) but it's fairly important that the package on bintray actually reflects the code in the github release... Perhaps only ever allow uploading new packages/versions rather than replacing?

**Comment by martinmoene** [comment]
Thanks @nathanaelg , this is clearly wrong and it was possible to happen as updating is a (still) a manual release step.

**Comment by martinmoene** [comment]
@nathanaelg I'll try to [release *gsl lite* 0.35.0](https://github.com/martinmoene/nonstd-lite-project/issues/23) soon and have conan and GitHub in sync again.

**Comment by martinmoene** [comment]
Note to self: come on then and do it.
