### ISSUE TITLE
Cleanup for 1.0

### ISSUE THREAD

**Issue by mbeutel** [gsl-lite/gsl-lite#178]
There are several occasions for code cleanup if we decide to make some breaking changes in a major version update.

- [x] Introduce a clear distinction between internal macros (implementation details, subject to change) and public macros (intended for public consumption), e.g. by giving internal macros a trailing `_`.
- [x] Remove currently unused macros: `gsl_REQUIRES_0()`, `gsl_REQUIRES_R()`, `gsl_DIMENSION_OF()`, probably more
- [x] Remove `gsl_REQUIRES_T()` in favor of `gsl_REQUIRES_A()`, and perhaps change that to the more idiomatic `typename enable_if<..., int>::type = 0`
- [x] Change default of `gsl_FEATURE_OWNER_MACRO` to 0 (only needed for C++98).
- [x] Change default of `gsl_CONFIG_ALLOWS_NONSTRICT_SPAN_COMPARISON` to 0 (consistent with C++20 spans).
- [x] `final_action<>` should not need a virtual destructor, and `final_action_return<>` and `final_action_error<>` should not inherit from `final_action<>`.
- [x] Change default of `gsl_CONFIG_NOT_NULL_EXPLICIT_CTOR` to 1 (thanks @petamas)

**Comment by petamas** [comment]
I'd also consider changing the default of gsl_CONFIG_NOT_NULL_EXPLICIT_CTOR to 1 (or removing the config option completely) - there's a not_null_ic class if someone wants the implicit constructor, and making it explicit ensures more type-safety (users have to manually write not_null, making them declare in writing that they are sure it won't be null).

**Comment by mbeutel** [comment]
Right, I missed that. Added it now, thanks.
