### ISSUE TITLE
[M-GSL]  Throwing copy and move constructors cause final_act to not execute the action

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#20]
On M-GSL, Eric Niebler: 

throwing copy and move constructors cause final_act to not execute the action [#283 ](https://github.com/Microsoft/GSL/issues/283).

The constructor of `final_act` [here](https://github.com/Microsoft/GSL/blob/master/include/gsl_util.h#L64) moves from argument `f` into member `f_`. If that throws, then the action is not executed, which is kinda the whole point of this utility. [This paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0052r2.pdf) shows how to do it right.

---

This paper: [P0052R2](http://wg21.link/p0052r2)
[Example code](https://github.com/PeterSommerlad/SC22WG21_Papers/tree/master/workspace/P0052_scope_exit) on Peter Sommerlad's GitHub

**Comment by jack17529** [comment]
@martinmoene  , please see weather I am understanding it right.
We are having problem in this move ctor -
`explicit final_act(F f) noexcept : f_(std::move(f)), invoke_(true) {}`

and this more specifically - `f_(std::move(f))` as it may throw an exception .

**Comment by martinmoene** [comment]
See M-GSL issue [finally() mishandles modifiable lvalues #125](https://github.com/Microsoft/GSL/issues/125)
See M-GSL PR [Reimplement final_act using the scope_exit design from P0052R5 #551](https://github.com/Microsoft/GSL/pull/551)

**Comment by mbeutel** [comment]
Related: https://github.com/microsoft/GSL/pull/977

**Comment by mbeutel** [comment]
Closed as obsolete. A modernization of `finally()` et al. is under way in #342.
