### ISSUE TITLE
span<> should have a .front() and .back()

### ISSUE THREAD

**Issue by ned14** [gsl-lite/gsl-lite#241]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4849.pdf says that `span<>` ought to have a `.front()` and a `.back()`. Please add them. Thanks.

**Comment by mbeutel** [comment]
Thanks for the report. This was now addressed by #244.

As far as I can see, the only thing still missing from C++20 span is static extents (tracked by #153), which will have to wait until the next major-version release because of ABI breakage.
