### ISSUE TITLE
GSL-Lite does not work on Apple Clang in Objective-C++ mode when exceptions are turned off

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#252]
The solution for #216 contains a minor bug. Currently, GSL-Lite uses either  `__EXCEPTIONS` or `__cpp_exceptions` to determine if exceptions are enabled during Clang compilation, depending on version:

```
#if gsl_BETWEEN(gsl_COMPILER_GNUC_VERSION, 1, 500) || gsl_BETWEEN(gsl_COMPILER_CLANG_VERSION, 1, 360) || gsl_COMPILER_APPLECLANG_VERSION
# ifdef __EXCEPTIONS
#  define gsl_HAVE_EXCEPTIONS  1
# else
#  define gsl_HAVE_EXCEPTIONS  0
# endif // __EXCEPTIONS
#elif gsl_COMPILER_GNUC_VERSION >= 500 || gsl_COMPILER_CLANG_VERSION >= 500
# ifdef __cpp_exceptions
#  define gsl_HAVE_EXCEPTIONS  1
# else
#  define gsl_HAVE_EXCEPTIONS  0
# endif // __cpp_exceptions
#elif gsl_COMPILER_MSVC_VERSION
# ifdef _CPPUNWIND
#  define gsl_HAVE_EXCEPTIONS  1
# else
#  define gsl_HAVE_EXCEPTIONS  0
# endif // _CPPUNWIND
#else
// For all other compilers, assume exceptions are always enabled.
# define  gsl_HAVE_EXCEPTIONS  1
#endif
```

This is broken in multiple ways:
- Clang [3.6, 5.0) is not handled at all (see `gsl_COMPILER_CLANG_VERSION >= 500`)
- Starting from Clang 3.6, `__EXCEPTIONS` is defined if either C++ or Objective-C exceptions are enabled,  which we handle in an OK way with vanilla Clang (apart from the previous bullet point), because we use `__cpp_exceptions` instead, but AppleClang is bundled with the pre-3.6 case, regardless of compiler version.

This means that GSL-Lite will not build if all of the following are true:
- AppleClang is used
- AppleClang is based on a Clang 3.6+ version
- C++ exceptions are disabled
- Objective-C exceptions are enabled
In this case, we derive that we _have_ C++ exception support, but in fact we do not, which causes all kinds of funny build errors:
```
.../gsl-lite.hpp:1229:5: error: cannot use 'throw' with exceptions disabled
throw fail_fast( message );
^
1 error generated.
```

Unfortunately, I could not find a free online AppleClang compiler, but I managed to simulate it on godbolt by giving "funny" parameters to Clang10. (The argument list is quite different from what we have in production, but the result is the same.)
See example here: https://godbolt.org/z/x4rYoo

According to this, we should use `#if __EXCEPTIONS && __has_feature(cxx_exceptions)` for both flavours (vanilla&apple) of clang: https://releases.llvm.org/3.6.0/tools/clang/docs/ReleaseNotes.html#the-exceptions-macro

---

I propose to change the decision tree to this:
```
#if gsl_COMPILER_CLANG_VERSION || gsl_COMPILER_APPLECLANG_VERSION
# if __EXCEPTIONS && __has_feature(cxx_exceptions)
#  define gsl_HAVE_EXCEPTIONS  1
# else
#  define gsl_HAVE_EXCEPTIONS  0
# endif // __EXCEPTIONS && __has_feature(cxx_exceptions)
#elif gsl_COMPILER_GNUC_VERSION
# if gsl_BETWEEN(gsl_COMPILER_GNUC_VERSION, 1, 500)
#  ifdef __EXCEPTIONS
#   define gsl_HAVE_EXCEPTIONS  1
#  else
#   define gsl_HAVE_EXCEPTIONS  0
#  endif // __EXCEPTIONS
# else
#  ifdef __cpp_exceptions
#   define gsl_HAVE_EXCEPTIONS  1
#  else
#   define gsl_HAVE_EXCEPTIONS  0
#  endif // __cpp_exceptions
# endif // gsl_BETWEEN(gsl_COMPILER_GNUC_VERSION, 1, 500)
#elif gsl_COMPILER_MSVC_VERSION
# ifdef _CPPUNWIND
#  define gsl_HAVE_EXCEPTIONS  1
# else
#  define gsl_HAVE_EXCEPTIONS  0
# endif // _CPPUNWIND
#else
// For all other compilers, assume exceptions are always enabled.
# define  gsl_HAVE_EXCEPTIONS  1
#endif
```

It has the drawback of not using the more-or-less standard __cpp_exceptions macro with CLANG, but it seems to work with every compiler so far, and I couldn't find any official documentation about the macro anyway. Naturally, I'll do some thorough testing before sending the PR using both the GitHub CI system and my company's specific builds.

**Comment by mbeutel** [comment]
Thank you for the careful analysis and the proposed fix.

I guess the first step towards better no-exceptions support is to add minimal tests for it. We'd need a test framework with support for death tests if we are to do any serious testing in this mode; but even a minimal compile-only test (as we do for CUDA) would be a good start.

**Comment by petamas** [comment]
I agree, there should be tests for it; but I do not think we need death tests, we have `gsl_CONFIG_CONTRACT_VIOLATION_CALLS_HANDLER` for this exact purpose. :)

I think instead of having a separate test suite, we should adapt our already existing test suite to be able to be tested with or without exceptions:
- introduce a new macro called `EXPECT_FAIL` in `gsl_lite.t.hpp`
- if exceptions are enabled, `EXPECT_FAIL` should be defined using `EXPECT_THROW`
- if exceptions are disabled, `EXPECT_FAIL` should be defined using an implementation of `fail_fast_assert_handler ` (eg. `fail_fast_assert_handler` sets a global error flag, and `EXPECT_FAIL` contains an `EXPECT` on that)
- replace `EXPECT_THROW` with `EXPECT_FAIL` in gsl_lite.t.hpp (where applicable, i.e. everywhere except test for `narrow`
- modify the cmake files to build&run all tests both with and without exceptions, defining the corresponding `gsl_CONFIG_CONTRACT_VIOLATION_XXX` macro

I can try to put something together, but I can't promise to do it anytime soon. (I think I may be able to, but I'm not sure.) Also, doing this may or may not catch this particular bug.

**Comment by petamas** [comment]
For now, I opened a PR containing the above fix; I think we should open a separate issue for the "Add -fno-exceptions tests to CI" task.

**Comment by petamas** [comment]
@mbeutel: Do I understand correctly, that the corresponding PR was merged in, so I can close the issue?

**Comment by mbeutel** [comment]
Yes, now that there's a separate issue about testing the no-exception mode, I guess this one can be closed.
