### ISSUE TITLE
not_null<T> should not have conversion to bool

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#258]
It's idiomatic to check a (raw or smart) pointer for `nullptr` by converting it to `bool`: `if (p) { ... }`. The purpose of `not_null` is to eliminate these checks when they're unnecessary because we already know the pointer cannot be `nullptr`, thus the conversion to `bool` will result in `true`.

However, the current version of the library allows `not_null<T>` to be converted to anything `T` can be converted into, including `bool`. This means that the following code happily compiles:

```
not_null<Thing*> p = ...;
if (p)
{
  // use p
} else {
  // !!! DEAD CODE !!!
}
```

I believe this goes directly against the purpose of this template. I propose to disallow conversion to `bool`, eg. by modifying `it_not_null_oracle` to `it_not_null_or_bool_oracle`. (The name is a work in progress.)

My main question is: should this behaviour be governed by a configuration macro, or should this be a breaking change? If the former, could you propose a good name for it? (I'm really bad at naming config switches.)

**Comment by mbeutel** [comment]
> The purpose of `not_null` is to eliminate these checks when they're unnecessary because we already know the pointer cannot be `nullptr`, thus the conversion to `bool` will result in `true`.

Even worse, it may fail with a postcondition assertion if the `not_null<>` object is in moved-from state. There is currently no legal way to check whether a `not_null<>` object is in moved-from state; if we permit an implicit conversion to `bool` to compile, we mislead the user to believe that such a check is possible.

> My main question is: should this behaviour be governed by a configuration macro, or should this be a breaking change?

In my opinion it's a bug that implicit conversion to `bool` was ever permitted, and any code that performs such a check is suspicious and likely broken. So I'd rather not add a switch.

---

(There are two schools of thought w.r.t. the interpretation and treatment of the moved-from state. Herb Sutter articulates his view in the article ["Move, simply"](https://herbsutter.com/2020/02/17/move-simply/), and Sean Parent argues against it in the comments. *gsl-lite*'s take on `not_null<>` is more in line with Sean Parent's view; moved-from objects are considered untouchable for purposes other than reuse or destruction, and any such use constitutes a bug, whereas Herb Sutter insists that the moved-from state is just another valid state of the object, and hence discovery of the state should be possible, and all invariants should still hold for this state.

In his subsequent article ["Invariants and Preconditions,"](https://www.justsoftwaresolutions.co.uk/cplusplus/invariants.html), Anthony Williams asks for more precision when wielding the term "invariant"; he argues that an invariant must hold at all times, and if some condition holds only if an object is not in the moved-from state, it is a not an invariant.)

**Comment by petamas** [comment]
> Even worse, it may fail with a postcondition assertion if the `not_null<>` object is in moved-from state. There is currently no legal way to check whether a `not_null<>` object is in moved-from state; if we permit an implicit conversion to `bool` to compile, we mislead the user to believe that such a check is possible.

You're right, I didn't even notice O_O

> In my opinion it's a bug that implicit conversion to bool was ever permitted, and any code that performs such a check is suspicious and likely broken. So I'd rather not add a switch.

I completely agree, I just wanted to make sure. `is_not_null_or_bool_oracle` PR's coming soon.

> Herb & Sean & ...

Based on your excerpt, I tend to agree with Sean, but I'd need to read up on it. (Also, `not_null` is simply not feasible with Herb's interpretation.) I'm amassing quite a reading list from our conversations here. :D Last time, I watched ~5 hours of Odin Holmes after you (or Martin?) mentioned him.
