### ISSUE TITLE
std::swap cannot swap a not_null with itself

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#259]
In C++11 (or higher) mode, this code fails to run with a contract violation:

```
int i = 12;
not_null< int* > p( &i );
std::swap(p, p);
```

The root cause is that `std::swap` is usually implemented more-or-less this way:

```
template <class T>
void swap(T& lhs, T& rhs) {
    T tmp = std::move(lhs);
    lhs = std::move(rhs);
    rhs = std::move(tmp);
}
```

Here, the second assignment invokes `p = std::move(p)` on a moved-from `not_null` if we call `swap(p,p)`, triggering the contract violation in the move constructor/assignment operator (since we're moving from an "empty" `not_null`).

I see multiple ways to resolve this:
1. implement `swap` in the `gsl` namespace, and say that people should use ADL instead of std::swap (not very user-friendly)
2. modify the check in the move constructors to allow self-assignment regardless of state (i.e. no contract violation when `this == &other`)
3. modify the check in the move constructors to allow moving from a moved-from `not_null` to a moved-from `not_null` (i.e. no contract violation when `this->data.ptr_==nullptr && other.data.ptr_==nullptr` - this might be tricky to implement because of the initializer list)

I tried to find out whether self-move-assignment should have a defined behaviour, but could not find any official stance on this. Potential variants:
- self-move-assignment should be undefined behaviour
- self-move-assignment should leave the object in an unspecified, but valid state
- self-move-assignment should leave the object in the same state as if it was simply moved from
- self-move-assignment should be a no-op

I also could not find any information about the standard classes' reaction to self-move-assignment.

Choosing Option 2, and assuming self-move-assignment of the standard smart pointers is a no-op under all implementations of the STL (which I think is true RN) seems to be the easiest route. We also need to decide if we consider self-copy-assignment valid.

**Comment by mbeutel** [comment]
> 1. implement `swap` in the `gsl` namespace, and say that people should use ADL instead of std::swap (not very user-friendly)

Actually the "two-step dance" is the only correct way to swap:

```c++
int i = 12;
not_null< int* > p( &i );
using std::swap;
swap(p, p);
```

Cf. http://ericniebler.com/2014/10/21/customization-point-design-in-c11-and-beyond/, https://www.codeproject.com/Articles/1245810/Avoid-the-std-step .

In fact I would add `swap()` as a hidden friend, not in the `gsl` namespace, so users are forced to call it via ADL.


> 2. modify the check in the move constructors to allow self-assignment regardless of state (i.e. no contract violation when `this == &other`)
> 
> 3. modify the check in the move constructors to allow moving from a moved-from `not_null` to a moved-from `not_null` (i.e. no contract violation when `this->data.ptr_==nullptr && other.data.ptr_==nullptr` - this might be tricky to implement because of the initializer list)

I'd rather not do either of these.


> I tried to find out whether self-move-assignment should have a defined behaviour, but could not find any official stance on this.

This is controversial; as far as I know no official stance exists.

My opinion is that self-move-assignment *should* be a no-op for valid objects and a contract violation for moved-from objects.


> We also need to decide if we consider self-copy-assignment valid.

That is uncontroversial: it must be valid.

**Comment by petamas** [comment]
> Actually the "two-step dance" is the only correct way to swap:

As far as I understand, every time people are talking about using the two-step dance, they're talking about using it _inside a template definition_.

Quote from https://quuxplusone.github.io/blog/2020/07/11/the-std-swap-two-step/ :
> Should I use the two-step in non-generic code?
> No.

However, his rationale is that "users should know if they wanna use std::swap or an overload for not_null", so I guess we're back where we started: if the user erroneously calls std::swap, they'll get a contract violation sometimes. In my understanding, the ADL-used `swap` should be a more performant/better implementation, but `std::swap` should work for everything, even if it's slow. (Also, since `std::swap` now uses moves, 99% of the custom `swap`s are unnecessary, because they were only needed to implement move semantics without using real move semantics.)

> My opinion is that self-move-assignment should be a no-op for valid objects and a contract violation for moved-from objects.

Why the second part? As far as I can tell, the main problem with self-move-assignment is that `lhs = std::move(rhs)` usually has two consequences:
- `lhs` will contain what was in `rhs` earlier
- `rhs` will be "empty" (moved-from)

If `lhs` and `rhs` are the same, these expectations contradict each other - except if `rhs` was already moved-from, and is left that way, so we satisfy both expectations. So for me, making "moved-from self-move-assignment" valid would be the obvious choice, and the validity of "valid self-move-assignment" the one in question.

>> We also need to decide if we consider self-copy-assignment valid.
> That is uncontroversial: it must be valid.

I haven't tested it yet, but I'm pretty sure `not_null` will signal a contract violation if the object is moved-from. (I tried to understand what would happen, but got lost in the constructor maze, hence issue #261)

**Comment by mbeutel** [comment]
> > Actually the "two-step dance" is the only correct way to swap:
> 
> As far as I understand, every time people are talking about using the two-step dance, they're talking about using it _inside a template definition_.
> 
> Quote from https://quuxplusone.github.io/blog/2020/07/11/the-std-swap-two-step/ :
> 
> > Should I use the two-step in non-generic code?
> > No.

Arthur's opinion on this is controversial, too, cf. the [reddit thread](https://www.reddit.com/r/cpp/comments/hpqbdz/what_is_the_stdswap_twostep/) about his article.

But I'll weaken my assertion a little and say: "*in the general case*, the 'two-step dance' is the only correct way to swap." Either way, calling `std::swap()` on `not_null<>` as in your original snippet is incorrect.


> > My opinion is that self-move-assignment should be a no-op for valid objects and a contract violation for moved-from objects.
> 
> Why the second part?

Yes, I guess I didn't think this through. Perhaps we should just make self-move-assignment a no-op. I'll have to think about it for a while.


> > > We also need to decide if we consider self-copy-assignment valid.
> 
> > That is uncontroversial: it must be valid.
> 
> I haven't tested it yet, but I'm pretty sure `not_null` will signal a contract violation if the object is moved-from.

Right, I should have been more precise. What I meant to say: unlike self-move-assignment of *valid* objects, which some people argue should be UB or leave the object in an unspecified state, self-copy-assignment of *valid* objects needs to be valid, and there's no controversy about it that I'm aware of.

One could say that the copy assignment `lhs = rhs` makes the following promises:

- `lhs` will be a copy of `rhs`, which usually means that `f(std::as_const(lhs))` is equivalent to `f(std::as_const(rhs))` for non-pathological purposes (such as printing the object address)
- `rhs` will be unchanged even in case of failure

Both are obviously satisfied if self-copy-assignment is valid and no-op for valid objects.

Self-copy-assignment of invalid objects should be a precondition violation in my opinion.

**Comment by mbeutel** [comment]
> Yes, I guess I didn't think this through. Perhaps we should just make self-move-assignment a no-op. I'll have to think about it for a while.

I still don't think self-move-assignment *should* be a no-op. However, making it a no-op will make code like yours above work. I believe the code is wrong because it calls `std::swap()` directly, but this is arguably commonplace, the failure will be unintuitive, and it probably won't teach users how to use `swap()` correctly. My main question would be: are there any bugs (i.e. errors in the program logic) that could be discovered if self-move-assignment of moved-from objects failed?

Generally disallowing to move already-moved-from objects is useful:

```c++
std::vector<Resource> validResources = ...;
consume(std::move(validResources.back()));
// bug: resource is in moved-from state but not removed from vector
validResources.push_back(...); // bug leads to precondition assertion failure if vector reallocates
```

But so far I couldn't think of a bug that would surface if self-move-assignment of moved-from objects was inhibited.

**Comment by mbeutel** [comment]
Sorry, hadn't meant for this to be closed already. `swap()` should now work but I don't have objections to unconditionally allowing self-move.
