### ISSUE TITLE
CUDA 11 with spans

### ISSUE THREAD

**Issue by codecircuit** [gsl-lite/gsl-lite#266]
The following snippet results into `nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)`

```cpp
// file.cu
#include <vector>
#include <gsl-lite/gsl-lite.hpp>

int main() {

	std::vector<gsl_lite::span<float>> vs;
	gsl_lite::span<float> s;
	vs.push_back(s);
}
```

Compile with `nvcc -I${GSL_INCLUDE_PATH} -Dgsl_CONFIG_DEFAULTS_VERSION=1 -std=c++17 file.cu -o out`
I used CUDA 11.0.194 with GCC 9.2.0 as host compiler. Seems to me like a Bug in the NVCC and it only occurs with c++17. With c++14 it works fine. Or does the GSL use some c++17 features there, which might not be supported by the nvcc?

**Comment by mbeutel** [comment]
Thank you for the report.

As a preparation I added CUDA 11.0 (as well as GCC 10, Clang 10, AppleClang 11.0.3) to CI in #267. All tests pass for C++14; the tests with C++17 enabled are currently running.

I compiled your test code manually on Windows with MSVC 19.2 and on Linux with GCC 9.3.0. Both compiled without error. Could you perhaps try to get NVCC to emit more logging info?

(It seems that CMake doesn't yet support `cuda_std_17` with NVCC; [CMAKE_CUDA_KNOWN_FEATURES](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CUDA_KNOWN_FEATURES.html) is reported empty. Do you know if this is supposed to work? As a stopgap solution I set `CUDA_STANDARD` to 17 on the target.)

**Comment by codecircuit** [comment]
I would be glad if `nvcc` would emit more logging. But it seems like an internal error message and its only that single output line, which is reported.

`CMAKE_CUDA_KNOWN_FEATURES` is also empty for me, but it seems to work anyway. So the `-std=c++17` is added to the command line, if add in the `CMakeLists.txt` the line `target_compile_features(mytarget PRIVATE cuda_std_17)`. But anyway the error is independent of CMake.

So for you the manual compilation worked on Linux. And also with the `-std=c++17` flag? For me it fails to compile on two different Linux systems.

**Comment by mbeutel** [comment]
Yes, it's a segfault in `cicc`. I could now reproduce it with your code and NVCC 11.0/GCC 9.2.0. The test suite still runs fine on the same machine though.

You can preprocess the source file and invoke `cicc` directly if you want to experiment with its arguments or look at the files it generates:

```
nvcc -E -I${GSL_INCLUDE_PATH} -Dgsl_CONFIG_DEFAULTS_VERSION=1 -std=c++17 file.cu -o file.cu.c++17.ii
${CUDA_ROOT}/nvvm/bin/cicc --c++17 --gnu_version=90200 --orig_src_file_name file.cu --allow_managed   -arch compute_52 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name file.fatbin.c -tused -nvvmir-library "${CUDA_ROOT}/nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name file.module_id --gen_c_file_name file.cudafe1.c --stub_file_name file.cudafe1.stub.c --gen_device_file_name file.cudafe1.gpu file.cu.c++17.ii -o file.ptx
```

There's not a lot of C++17-specific code in `span<>`, in fact I cannot think of anything other than the deduction guides (which shouldn't be invoked by your example code). I guess the error is triggered by C++17-specific bits in the standard library.

Your best bet is probably to submit a bug report to NVIDIA.

**Comment by codecircuit** [comment]
I further extracted the part of the GSL, which causes the compile error. Now here is a snippet without the include of the
GSL header, which causes the core dump:

```cpp
// file2.cu
#include <vector>
#include <type_traits>

template< class C, class E >
struct is_compatible_container : std::bool_constant <true>{};

template< class T >
struct span
{
    span() {}

	// Remove this constructor and cicc does not core dump any more.
	// The `&&` operator within the template causes the core dump in combination with
	// the inheritance from std::bool_constant
    template< class Container
        , typename std::enable_if<
             is_compatible_container< Container, T >::value
             && std::bool_constant<true>::value, int >::type = 0
    >
    span( Container const & cont ) {}
};

int main() {
	std::vector<span<float>> vs;
	span<float> s;
	vs.push_back(s);
}
```

**Comment by mbeutel** [comment]
Nice work. And if we replace the `&&` with [`std::conjunction<>`](https://en.cppreference.com/w/cpp/types/conjunction) the error seems to go away:

```c++
    template< class Container
        , typename std::enable_if<
             std::conjunction< is_compatible_container< Container, T >,
                 std::bool_constant<true> >::value, int >::type = 0
    >
```

Luckily we have a polyfill for `std::conjunction<>`/`std::disjunction<>`/`std::negation<>` (`gsl::std17::conjunction<>` etc.) so we can probably replace Boolean operators in SFINAE conditions with these. This is often desired anyway because `std::conjunction<>` and `std::disjunction<>` short-circuit and can thus avoid unnecessary instantiations.

PRs for such a change are welcome :) But regardless of that, would you mind issuing a bug report with NVIDIA?

**Comment by codecircuit** [comment]
Bug Report with NVIDIA https://forums.developer.nvidia.com/t/cicc-core-dump-with-std-enable-if-and-boolean-evaluation-in-template-expressions/145330

**Comment by mbeutel** [comment]
@codecircuit: Has this since been addressed by NVIDIA? If so, I'd like to close this issue.

**Comment by codecircuit** [comment]
Works now with CUDA 11.2.67 and gcc 9.2.0.
