### ISSUE TITLE
No constexpr default span<> constructor in gcc 5.4

### ISSUE THREAD

**Issue by KazDragon** [gsl-lite/gsl-lite#270]
This looks to be a consequence of https://github.com/gsl-lite/gsl-lite/commit/56aff97cdd4f0321252ce8e62aac0dce1a95588a

g++ 5.4 (currently default with Ubuntu 16.04, AIUI) can no longer construct a constexpr empty span.  This works in 0.34.

Experimentally, I changed the restriction on gsl_HAVE_CONSTEXPR_14 to 540 instead of 600, and then had to remove the constexpr annotation from fail_fast_assert because std::terminate is not a constexpr function.  After this, my program worked again.

If you like, I can fork/pr.

**Comment by mbeutel** [comment]
Thanks for the report. I can confirm the problem, cf. https://gcc.godbolt.org/z/We9cbW.

I think the correct fix would be
```diff
-    gsl_api gsl_constexpr14 span() gsl_noexcept
+    gsl_api gsl_constexpr span() gsl_noexcept
```

A PR would be welcome. If you submit one, could you also add a simple test to the test suite (in test/span.t.cpp) so we can avoid regressions?

**Comment by KazDragon** [comment]
That's even simpler.  I like it!  I'll give it a shot and I'll submit a PR as soon as I confirm the fix.

**Comment by KazDragon** [comment]
Confirmed.  There were a few other issues in my own code, but that was mostly due to one of the constructors being deprecated.  No problem.  PR incoming.

**Comment by mbeutel** [comment]
Thank you for the contribution!
