### ISSUE TITLE
GCC 11 Internal Compiler Error for relatively simple not_null example

### ISSUE THREAD

**Issue by viravera** [gsl-lite/gsl-lite#281]
Hello, 

The following example triggers an ICE in GCC 11 trunk in C++20 mode: https://godbolt.org/z/Y8n93K
Note that if you exchange gsl-lite for the Microsoft GSL implementation (and change the associated header), no ICE is triggered.

It may be reproduced on the latest trunk with the following command: g++-11 --std=c++20 test.cpp

I've reported the bug on the GCC tracker here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99132

I did not minify the reported GCC bug below the level of not_null inclusion, so the bug  report on the GCC bugzilla may need to be simplified to reduce it to a smaller test case for the GCC team to be able to resolve it.

UPDATE: The GCC team has expertly reduced the issue further. It occurs in any construct similar to the following:
```
template <class T> struct A { T c; };
template <class T> struct B {
  A<T> d;
  constexpr T operator->() { return d.c; }
  B(B &&);
};
struct C {
  virtual void foo ();
  void bar (B<C *> h) { h->foo (); }
};
```
I believe they will resolve the issue on their end, but I think it should be kept open for tracking here until they do; if this bug remains in the final release of GCC 11, a workaround would be needed in gsl-lite.

Thank you for your work; your library is very useful.

Full example source follows: (test.cpp)
-----------------------------------------------------------------------------------------------------------
```
#include <gsl/gsl-lite.hpp>
//#include <gsl/pointers> //Enable this header instead to switch to Microsoft GSL

class Source;
class Sink
{
public:
    virtual void attachSource(gsl::not_null<Source *>) {}
};

class Source
{
public:
    virtual void attachSink(gsl::not_null<Sink *> sink)
    {
        sink->attachSource(this);
    }
};

int main(int, char**)
{
    return 0;
}
```

**Comment by mbeutel** [comment]
Thank you for the meticulous report, and thanks for cross-linking the GCC issue. I'll keep an eye on the GCC bug, though I hope we can do without a workaround.
We don't have CI for GCC 11 yet, but it should be relatively easy to add. I'll try to address this soon. (I'm not keen to make any promises given my current workload, but next week might work.)

**Comment by viravera** [comment]
No problem! The GCC team has fixed this bug (Thanks Jakub!), so I'm closing it here. Glad this didn't need a workaround :)
