### ISSUE TITLE
Reduce the weight of the header file

### ISSUE THREAD

**Issue by mpusz** [gsl-lite/gsl-lite#288]
I am in the process of profiling compilation times of my mp-units library. Even though it is quite compile-time heavy by itself, it seems to spend a lot of time on the processing of the `gsl-lite.hpp` header file.

Could you please consider reducing the "weight" of the header file to improve compilation times? Most of the time (about 85%) is spent on the `<algorithm>` header parsing just to get `swap`, `equal`, `lexicographical_compare`.

![image](https://user-images.githubusercontent.com/506260/111356817-05bf5980-8689-11eb-8baf-fce0f7a1e23c.png)

Maybe an in-place custom implementation could be used instead?

Alternatively, the header could be split into a few smaller ones that will include only what they use but personally, I think it is a worse idea.

**Comment by mbeutel** [comment]
Thank you for the suggestion. I'm open to PRs that reduce the weight of *gsl-lite*, and I'd be happy to do away with the `<algorithm>` dependency.

Personally, I'd prefer if *gsl-lite* wasn't a single-header library, but I understand this is a valuable feature for some users.

**Comment by mbeutel** [comment]
The \<algorithm\> dependency is now gone (cf. #290). Could you please re-run your analysis?

I'm always interested in ways to further reduce the weight of the main header, but I think we can't really do away with any of the other standard library headers we depend on.

**Comment by mpusz** [comment]
Thanks! Here is the latest analysis for the same file:

![image](https://user-images.githubusercontent.com/506260/112199484-82fd4800-8c0e-11eb-8b23-f81c334885da.png)

The processing of the header is much faster now :-)

If you would look for more optimizations in the future most of the time is now spent in `iterator` and `memory` headers.

**Comment by mbeutel** [comment]
Great, thanks for the update.

We can't do without \<memory\> unless we sacrifice the `make_unique()` polyfill. But we can probably remove \<iterator\>: we also include \<array\>, and `std::array<>::reverse_iterator` is defined to be a specialization of `std::reverse_iterator<>`, so we can presumably take for granted that `std::reverse_iterator<>` is available without specifically including \<iterator\>. I'll give this a try.

How large is the impact of these two headers, quantitatively?

**Comment by mpusz** [comment]
`<iterator>` is the first big subcomponent and the `<memory>` the second one on the above graph.
You can try to unzip the attached file and load it via `chrome://tracing/` in Chrome.

[glide_computer.cpp.json.zip](https://github.com/gsl-lite/gsl-lite/files/6192522/glide_computer.cpp.json.zip)

**Comment by mpusz** [comment]
It is easy to gather the stats by yourself too. Just add `-ftime-trace` to the clang command line (`CXX_ARGS`) and it will generate a json file for each TU.

**Comment by mbeutel** [comment]
Thank you, that is all very useful information. #295 has now removed the \<iterator\> dependency. However, from looking at the trace you provided, I doubt it will gain as much because most of the weight ultimately comes from \<string\>.

I think we can't really do without \<string\> or \<memory\> without cutting the feature set of *gsl-lite*, so I'd consider this issue addressed at this point. Also, before we attempt to go any further, I'd like to see a wider variety of real-world data. \<algorithm\> and \<iterator\> were relatively low-hanging fruits, but is their removal is actually beneficial in real code? \<algorithm\>, for example, is also included by \<fmt/format.h\> in your trace.

**Comment by mpusz** [comment]
Thanks! I think it helps a lot. Especially for simple files that do not include a lot of headers. I also agree that it does not have the sense to continue with more changes as this would impact the library design too much. Hopefully, C++ modules will arrive soon and will address this issue once and for all...

**Comment by mbeutel** [comment]
> I think we can't really do without <string> or <memory> without cutting the feature set of _gsl-lite_

In [v1.0](https://github.com/gsl-lite/gsl-lite/releases/tag/v1.0.0), `string_span` was made an opt-in feature, so we no longer require the headers `<ios>` and `<string>` by default:

https://github.com/gsl-lite/gsl-lite/blob/c369a3d9da668a04048d557dd4d1a625a6a62c8b/include/gsl-lite/gsl-lite.hpp#L1309-L1312
