### ISSUE TITLE
gsl_FEATURE_GSL_LITE_NAMESPACE not working

### ISSUE THREAD

**Issue by BMBurstein** [gsl-lite/gsl-lite#320]
The setting `gsl_FEATURE_GSL_LITE_NAMESPACE`, and the whole `gsl_lite` namespace thing mentioned in the README is not working at all

**Comment by mbeutel** [comment]
Works for me:

```c++
#include <gsl/gsl-lite.hpp>
int main() {
    double d = 42.;
    float f = gsl_lite::narrow_cast<float>(d);
}
```
compiled with `g++ -Dgsl_FEATURE_GSL_LITE_NAMESPACE=1`
(cf. https://gcc.godbolt.org/z/9s9hhGj4c)

Could you perhaps be more specific about your problem?

**Comment by BMBurstein** [comment]
I must have configured something wrong. Sorry about the noise

**Comment by mbeutel** [comment]
No problem :) Next time, please supply a minimal repro (code example + command line for compiler invocation) along with a bug report.
