### ISSUE TITLE
Definition of `fail_fast` and of `narrowing_error` triggers `clang`'s `-Wweak-vtables`

### ISSUE THREAD

**Issue by mrahn** [gsl-lite/gsl-lite#322]
As ` fail_fast` and ` narrowing_error` are deriving from `std::logic_error` and from ` std::exception` respectively, they both have a vtable. In a header-only library there is no compilation unit, which implies the vtables are emitted in every client compilation unit, putting burden to the linker to understand this is not a duplicate definition. That is what the warning is about.

Solution
- Disable the warning locally.

Alternatives:
- introduce a compilation unit (NO because: header-only is wanted)
- do not use a custom exception (NO because: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e14-use-purpose-designed-user-defined-types-as-exceptions-not-built-in-types)
- introduce ` template<typename = void> fail_fast ...` and ` throw fail_fast<>` (NO because: Introduces complexity to hide a warning is never a good idea.)
- disable all warnings (NO because: 1. Unclear how that would even work if header is copied by clients. 2. Warnings are friends.)

References:
- See https://github.com/mrahn/test_gsl_lite_weak_vtables for a reproducer (which is basically: include the header with ` -Wweak-vtables` on)
- See https://github.com/gsl-lite/gsl-lite/pull/321 for a workaround that disables all warnings for the ` gsl-lite`  header

**Comment by mbeutel** [comment]
This should now be fixed. I'm sorry it took so long.
