### ISSUE TITLE
Tests fail to compile due to -Werror=type-limits when char is unsigned

### ISSUE THREAD

**Issue by musicinmybrain** [gsl-lite/gsl-lite#337]
On Fedora Linux Rawhide, with GCC 13.0.1, while testing gsl-lite 0.41.0, we’re seeing that `test/lest_cpp03.hpp` fails to compile with an error from `-Werror=type-limits` on our non-x86 architectures (`aarch64`, `ppc64le`, `s390x`).

```
In file included from /builddir/build/BUILD/gsl-lite-0.41.0/test/gsl-lite.t.hpp:104,
                 from /builddir/build/BUILD/gsl-lite-0.41.0/test/emulation.t.cpp:20:
/builddir/build/BUILD/gsl-lite-0.41.0/test/lest_cpp03.hpp: In function 'bool lest::unprintable(char)':
/builddir/build/BUILD/gsl-lite-0.41.0/test/lest_cpp03.hpp:707:46: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  707 | inline bool unprintable( char c ) { return 0 <= c && c < ' '; }
      |                                            ~~^~~~
```

This seems to be happening because `char` is equivalent to `signed char` on `i686` and `x86_64`, but is equivalent to `unsigned char` on the other platforms. The useless comparison is not a real problem here, but the failure to compile is.

I am not sure why we are seeing this in 0.41.0 but not in 0.40.0. Nothing stands out in the [changes](https://github.com/gsl-lite/gsl-lite/compare/v0.40.0...v0.41.0) as potentially relevant.

There is existing logic to suppress this warning on “`GNU`” compilers, but only for old compiler versions:

https://github.com/gsl-lite/gsl-lite/blob/755ba124b54914e672737acace6a9314f59e8d6f/test/MakeTestTarget.cmake#L264-L266

Should we just make that unconditional, like `-Wno-long-long` and `-Wuseless-cast`?

**Comment by mbeutel** [comment]
Thank you for the report. The problem might be related to [this change](https://github.com/gsl-lite/gsl-lite/compare/v0.40.0...v0.41.0#diff-a7de0ab295be3cbd5bbf4552e64a470adf70bd1e8d8929c00e52e77214721dfbL300) to the PCH setup. Previously, we had simply set gsl-lite.t.hpp as the precompiled header; but apparently this didn't interact well with the warning suppressions in that header file; at least I had to address several previously unseen warnings after making these changes.

As a general rule, I would like to avoid unconditional warning suppressions for current compiler versions. "-Wno-long-long", being relevant only for C++98, is an exception; "-Wuseless-cast" unconditionally *enables* the warning which is fine.

If the warning appears only once, I'd prefer to work around locally, either by suppressing it:

```c++
inline bool unprintable( char c )
{
#if defined (__GNUC__)
# pragma GCC diagnostic suppress "-Wtype-limits"  // comparison is always true due to limited range of data type
#endif // defined (__GNUC__)
    return 0 <= c && c < ' ';
}
```
or by casting `c` to `signed char`:
```c++
inline bool unprintable( char c ) { return 0 <= static_cast<signed char>(c) && c < ' '; }
```

Would you mind verifying if either of these fixes the issue, and possibly issuing a PR?

**Comment by martinmoene** [comment]
An intermediate step to suppress _lests_'s  warnings could perhaps be to handle it as a system header. See e.g. [this commit of string_view lite](https://github.com/martinmoene/string-view-lite/commit/b0e272a66aaea973db3f21aff8e486e23c967719).

**Comment by musicinmybrain** [comment]
> Thank you for the report. The problem might be related to [this change](https://github.com/gsl-lite/gsl-lite/compare/v0.40.0...v0.41.0#diff-a7de0ab295be3cbd5bbf4552e64a470adf70bd1e8d8929c00e52e77214721dfbL300) to the PCH setup. Previously, we had simply set gsl-lite.t.hpp as the precompiled header; but apparently this didn't interact well with the warning suppressions in that header file; at least I had to address several previously unseen warnings after making these changes.

Thanks for explaining that; it seems like a plausible root cause.

> As a general rule, I would like to avoid unconditional warning suppressions for current compiler versions. […]
> 
> If the warning appears only once, I'd prefer to work around locally, either by suppressing it:
> 
> […]
> 
> or by casting `c` to `signed char`:
> 
> […]
> 
> Would you mind verifying if either of these fixes the issue, and possibly issuing a PR?

Thanks for the suggestions. Both of these look reasonable; if you have no particular preference, I think I prefer the cast. I’ve tested it as a patch and opened a PR.

**Comment by musicinmybrain** [comment]
> Thanks for the contribution. Do you need a patch release (v0.41.1) as soon as possible? If not, I'd let it sit for a few days before issuing a release in case there is more fallout.

There is no hurry at all. Thanks for working on this.
