### ISSUE TITLE
Allow `not_null<void*>` and related.

### ISSUE THREAD

**Issue by BenFrantzDale** [gsl-lite/gsl-lite#340]
Presently, `not_null<Ptr>`'s `operator*` is required to exist, making `not_null<void*>` not viable.

This seems to address at least the ability to construct a `not_null<void*>`, although conversion with stronger types isn't there:
```c++
    template <typename ElementType = element_type>
    gsl_NODISCARD gsl_api gsl_constexpr14
        std::enable_if_t<not std::is_same_v<void, std::remove_cv_t<ElementType>>, std::add_lvalue_reference_t<element_type>>
    operator*() const
    {
        return *data_.ptr_;
    }
```

**Comment by mbeutel** [comment]
Thanks for the report, and sorry for taking a while to respond.

I can add `not_null<void*>` support along the lines of what you suggest, but I'm at loss how the type conversion should be handled. Typed pointers are not constructible from `void*` (i.e. `int* i = (void*)nullptr;`), yet they are explicitly convertible with `static_cast<>`. I don't think there is a way to mimick this distinction for a user-defined type.

A conversion sequence via `gsl::as_nullable()` would of course be possible:
```c++
int i = 42;
void* vp = &i;
auto nvp = gsl::not_null(vp);
void* vp2 = gsl::as_nullable(nvp);
int* ip = static_cast<int*>(vp2);
```

I'm open towards suggestions on how to support casting in a less cumbersome way.

**Comment by mbeutel** [comment]
The only thing I could think of so far is a set of casting functions `gsl_lite::static_pointer_cast<>()`, `gsl_lite::dynamic_pointer_cast<>()`, `gsl_lite::const_pointer_cast<>()`, `gsl_lite::reinterpret_pointer_cast<>()`, in analogy to the pointer casting functions for `std::shared_ptr<>` (cf. https://en.cppreference.com/w/cpp/memory/shared_ptr/pointer_cast).

**Comment by BenFrantzDale** [comment]
Yeah. For my use case, all I was looking for is to be able to store a pointer that I know can't be null but that points to `void`, and was disappointed to be unable to represent that. I think you are right about not being able to emulate the conversions of `void*` (although I almost started a StackOverflow thread on it; it would be interesting to fully understand those conversion rules!)

So yeah, I think I'm just proposing disabling `operator*` on pointers to `void`.

**Comment by BenFrantzDale** [comment]
Awesome! Thanks!

**Comment by BenFrantzDale** [comment]
Thanks for the fix! Unfortunately, I went to use this in a production application and found that it doesn't cover all the bases: Now I'm finding I want to have a `not_null<std::unique_ptr<void*, void(*)(void*)>>` or even a `not_null<std::unique_ptr<const void*, void(*)(const void*)>>` or a `not_null<std::shared_ptr<const void>>`.

I *think* this can be allowed just by templating `operator*` so that SFINAE takes over, so it looks like this:
```cpp
    template <typename ResultType = decltype(*data_.ptr_)>
    gsl_NODISCARD gsl_api gsl_constexpr14 ResultType
    operator*() const
    {
        static_assert(std::is_same_v<ResultType, decltype(*data_.ptr_)>, "No funny business with `ptr.operator*<foo>()`.");
        gsl_Assert( data_.ptr_ != gsl_nullptr );
        return *data_.ptr_;
    }
```
Does that sound right?

**Comment by BenFrantzDale** [comment]
Thanks again. To follow up on these, I know these are obscure uses, but there are some very cool things you can do with `std::shared_ptr<void>`, like keep heterogeneous cache handles alive. So like `LruQueue<not_null<std::shared_ptr<const void>, 8>` holds up to 8 of... something, anything! And of course, `std::unique_ptr<void*>` isn't allowed 'cause it can't delete it, but `std::unique_ptr<void*, void(*)(void*)>` is.

**Comment by BenFrantzDale** [comment]
> Thanks, that sounds like a useful pattern to remember. I suppose the `LruQueue<>` holds the strong pointer and any other references are `weak_ptr<>` ones then?

Something like that. `LruQueue` isn't actually the case I need `not_null` for, but it's a good example of a totally-sane use of `std::unique_ptr<void>`. (My `LruQueue` use case is that my cache produces `nn_shared_ptr<const T>`, and generally that keeps the `T` alive, but if you want to extend the lifetime, you can put it in a `LruQueue<nn_shared_ptr<const void>>` and then ask the cache for it again and it'll find it.)

The use case today was in writing a type-erased class where I wanted to hold `nn_unique_ptr<void, void(*)(void*)>` and the containing class knows enough to know what type it has (or that it's pointing to a `Base` of some kind, so it can cast to `Base&` and then `dynamic_cast<Derived*>`).
