### ISSUE TITLE
Behavior of  narrow() on discarding information

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#52]
In [release 0.14.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.14.0) of *gsl lite* `gsl_CONFIG_CONTRACT_VIOLATION_TERMINATES` and `gsl_CONFIG_CONTRACT_VIOLATION_THROWS` also govern the behavior of `narrow()` when a conversion discards information (issue #50 ). 

**This change** to the behavior of `narrow()` **is a breaking change**: on discarding information `narrow()` used to always throw, whereas it now only throws if the *non-default* `gsl_CONFIG_CONTRACT_VIOLATION_THROWS` is selected. Would more or different control over `narrow()`'s behavior be required?

**Comment by martinmoene** [comment]
For example:

Maintain compatibility with M-GSL and restore default  throwing  behavior of narrow() and provide:

-  `gsl_CONFIG_NARROW_DISCARD_THROWS` / `gsl_CONFIG_NARROW_DISCARD_TERMINATES` 
- `gsl_NO_EXCEPTIONS` which sets
  - `gsl_CONFIG_CONTRACT_VIOLATION_TERMINATES`
  - `gsl_CONFIG_NARROW_DISCARD_TERMINATES`

or only provide the following to be able to have old behavior compatible with M-GSL:
- `gsl_CONFIG_NARROW_DISCARD_THROWS`

or ...

**Comment by mbeutel** [comment]
I agree that your implementation of `narrow()` is probably more useful, but it clearly isn't what the Core Guidelines specify:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-204

> ```c++
> double d = 7.9;
> ```
> ...
> The guidelines support library offers a `narrow_cast` operation for specifying that narrowing is acceptable and a `narrow` ("narrow if") that throws an exception if a narrowing would throw away information:
> 
> ```c++
> i = narrow_cast<int>(d);   // OK (you asked for it): narrowing: i becomes 7
> i = narrow<int>(d);        // OK: throws narrowing_error
> ```

So there is no way to get narrowing with a fail-fast check. I think I'd have specified `narrow<>()` such that it uses `Expects()` to guard against loss of information, and an additional `narror_or_throw<>()` which throws `narrowing_error`.

Cf. https://github.com/microsoft/GSL/issues/802.

**Comment by mbeutel** [comment]
I agree that your implementation of `narrow()` is probably more useful, but it clearly isn't what the Core Guidelines specify:

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#note-204

> ```c++
> double d = 7.9;
> ```
> ...
> The guidelines support library offers a `narrow_cast` operation for specifying that narrowing is acceptable and a `narrow` ("narrow if") that throws an exception if a narrowing would throw away information:
> 
> ```c++
> i = narrow_cast<int>(d);   // OK (you asked for it): narrowing: i becomes 7
> i = narrow<int>(d);        // OK: throws narrowing_error
> ```

So there is no way to get narrowing with a fail-fast check. I think I'd have specified `narrow<>()` such that it uses `Expects()` to guard against loss of information, and an additional `narror_or_throw<>()` which throws `narrowing_error`.

Cf. https://github.com/isocpp/CppCoreGuidelines/issues/1498 and https://github.com/microsoft/GSL/issues/802.

**Comment by mbeutel** [comment]
From https://github.com/isocpp/CppCoreGuidelines/issues/1498:
> Editors' call: Our view is that narrow is like to_integer(string) -- if the input contains an invalid value (e.g., to_integer("hello")) then we should throw a run-time error. This means that narrow should not use an Expects, it is not a precondition violation.

So perhaps our `narrow<>()` shouldn't do that either.

I'm inclined to add a configuration option `gsl_CONFIG_NARROW_IS_PRECONDITION_CHECK`, have it default to 0 (current behavior), and to change the default to 1 (conforming behavior) for the next major version.

I do share the desire for a narrowing cast that uses a precondition check. Perhaps we can add one as an extension, but I guess it should have a different name.
