### ISSUE TITLE
Provide compatibility with MS GSL string_span<>?

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#6]
Note gsl-lite string_span vs. MS GSL string_span<>.

Provide gsl_CONFIG_STRING_SPAN_TEMPLATE or some such?

See also issue #5 "add gsl.h to include?"

**Comment by mbeutel** [comment]
I'd like to introduce `string_span<>` when we break compatibility for version 1.0. We can introduce a compatibility macro to allow `string_span`, but that would affect ABI and hence trigger a warning (cf. #179).

**Comment by mbeutel** [comment]
Though apparently M-GSL maintainers aren't happy with the `<>` either:
https://github.com/isocpp/CppCoreGuidelines/issues/1126

**Comment by mbeutel** [comment]
`string_span<>` was now deprecated by M-GSL due to having been removed from the C++ Core Guidelines:
https://github.com/microsoft/GSL/pull/931

I wonder if we should also deprecate `string_span`, along with `zstring_span` (cf. #282, #283, #287)? Or do we keep and foster them as a *gsl-lite* extension?

**Comment by mbeutel** [comment]
M-GSL has since removed `string_span<>` entirely, cf. https://github.com/microsoft/GSL/pull/1074. So I'm in favor of deprecating our `string_span` as well.

**Comment by mbeutel** [comment]
Following M-GSL, which deprecated and subsequently removed `string_span<>` and `zstring_span<>`, we now deprecate `string_span` and `zstring_span` as well. Deprecation messages can be suppressed by setting [`gsl_CONFIG_DEPRECATE_TO_LEVEL`](https://github.com/gsl-lite/gsl-lite#other-configuration-macros) accordingly.
