### ISSUE TITLE
Fix hash<std::size_t> for Clang Xcode on Mac OS X 

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#63]
Dave Tallman reports for f2a9c30eb501e761412b225c1d023941f21d5f25 (Release 0.19.0+, fixed in 0.21.0):

Compile error goes away when the call to hash<std::size_t>() is removed (this is a no-op in clang and gcc, but not in Windows).

```
In file included from 3rdparty/gsl-lite/include/gsl.h:25:
3rdparty/gsl-lite/include/gsl/gsl-lite.h:2164:16: error: implicit instantiation of undefined
      template 'std::__1::hash<unsigned long>'
        return hash<std::size_t>()( gsl::to_integer<std::size_t>( v ) );
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3159:29: note:
      template is declared here
template <class _Tp> struct hash;
                            ^ 
```

**Comment by martinmoene** [comment]
A coworker of Dave reports:

I noticed something in the messages we got:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3159:29: note:
      template is declared here
template <class _Tp> struct hash;
```
It says "template is declared here" for a definition inside <memory>, which is not the true definition. The real declaration is in <__functional_base>, line 41:
```
template <class _Tp> struct _LIBCPP_TYPE_VIS_ONLY hash;
```
This seems to violate the ODR, having two different definitions for the same thing (they might be identical, or not, depending on the definition of _LIBCPP_TYPE_VIS_ONLY). The specializations for unsigned long, etc., all have the _LIBCPP_TYPE_VIS_ONLY qualifier, so the bad definition could make the hash specializations not applicable.

This seems wrong. I wonder what would happen if the improper definition in memory was commented out (memory includes <__functional_base> so it can see the true definition).

We probably don't want to change the STL code for <memory> in the long run. I think I can work around it by putting the following in gsl-lite.h:

```
#include <memory>
#include <functional>
```
By making sure that functional is included after memory, we set things up so the bad hash definition will be overwritten by the correct one. Then the hash usage in gsl-lite.h should pick up on the good definition.

If this works, we have exposed a serious bug in Clang.

---------------
Dave adds: This worked for us, so you might be able to keep the hash after all.

**Comment by martinmoene** [comment]
In [Release 0.21.0](https://github.com/martinmoene/gsl-lite/releases/tag/v0.21.0) I removed the call to `hash<std::size_t>` from the hash for `byte`. 

Pondering what to do next: keeping  `hash<std::size_t>` out or adding`<functional>` in an *anti-lexical* order...

**Comment by solvingj** [comment]
Did anyone ever report this to Clang? If so, is there an open issue? We just hit same issue with hash.

**Comment by martinmoene** [comment]
I haven't looked into that.

**Comment by solvingj** [comment]
I just sent an email to the bug report email.  Hope they get it.

**Comment by mbeutel** [comment]
I think our

```c++
template<>
struct hash< ::gsl::byte >
{
public:
    gsl_NODISCARD gsl_constexpr std::size_t operator()( ::gsl::byte v ) const gsl_noexcept
    {
        return ::gsl::to_integer<std::size_t>( v );
    }
};
```

should really be something like

```c++
template<>
struct hash< ::gsl::byte >
{
public:
    gsl_NODISCARD gsl_constexpr std::size_t operator()( ::gsl::byte v ) const gsl_noexcept
    {
        return std::hash<std::underlying_type<::gsl::byte>::type>{ }( v );
    }
};
```

but that alters the hash code and thus is a breaking change, due for version 1.0. Any issues with Clang/libc++ will probably surface when we make this change.
