### ISSUE TITLE
Return remaining range from gsl::copy()

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#64]
See M-GSL PR 422.

**Comment by mbeutel** [comment]
I'm happy to consider a PR for this- But given that

* the Core Guidelines only mention a `copy()` function returning `void`,
* M-GSL didn't take https://github.com/microsoft/GSL/pull/422 so far,
* the logic for figuring out the span size is non-trivial and needs comprehensive testing,
* nobody actually seems to have a need for this,

I'd rather not spend cycles on it myself.
