### ISSUE TITLE
Add span_p<> (p: predicate)

### ISSUE THREAD

**Issue by martinmoene** [gsl-lite/gsl-lite#9]
See C++ Core Guidelines, [F.24: Use a span<T> or a span_p<T> to designate a half-open sequence](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-range).

**Comment by mbeutel** [comment]
The Core Guidelines specify `span_p<>` like this:

> - `span_p<T>` // `{p, predicate}` `[p:q)` where `q` is the first element for which `predicate(*p)` is true

But I don't see why this should be a separate type, not simply a `span<>` algorithm:

```c++
template <typename T, typename PredT>
span<T> take_until( span<T> s, PredT const& pred )
{
    ...
}
```

Cf. https://github.com/isocpp/CppCoreGuidelines/issues/1518

**Comment by mbeutel** [comment]
This is currently too under-specified for us to do anything with it.

I'm closing this issue now, but I'm happy to reopen if anyone can produce (1) a reasonable interpretation of the specification and (2) a use case.
